#!/bin/bash
if [ -z "$1" -o -z "$2" -o -z "$3"]
then
#pathDir is the directory into which to symlink all the executables

#folderLinkDir is the directory into which symlinks to newly inited repos will
#be placed

	echo "Usage: $(basename) pathDir folderLinkDir configDir"
fi

echo "Linking files in ./bin subfolder of current folder into $1"

binfolder="$(readlink -f $(dirname $BASH_SOURCE)/bin)"

#Make the storage folder writable by everyone
chmod a+w "$2"

#Set the files executable
chmod a+x "$binfolder"/*

#Link the files into the bin folder
for file in "$binfolder"/*
do
	ln --symbolic --target-directory="$1" "$file" 
done

#Create the configuration file
echo "$2/" > "$3"/newstools.conf

