#!/bin/bash

#dgit--A primitive git GUI
#Copyright (C) 2011-2012  andyg0808

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [[ -z "$1" || -z "$2" || -z "$3" ]]
then
#pathDir is the directory into which to symlink all the executables

#folderLinkDir is the directory into which symlinks to newly inited repos will
#be placed

	echo "Usage: $(basename $0) pathDir folderLinkDir configDir"
	exit 1
fi

echo "Linking files in ./bin subfolder of current folder into $1"

binfolder="$(readlink -f $(dirname $BASH_SOURCE)/bin)"

#Make the storage folder writable by everyone
chmod a+w "$2"

#Set the files executable
chmod a+x "$binfolder"/*

#Link the files into the bin folder
for file in "$binfolder"/*
do
	ln --symbolic --target-directory="$1" "$file" 
done

#Get absolute path for the folderLinkDirectory
flinkdir="$(readlink -f $2)"

#Grab the standard dgit-locations configuration file which provides the filename
#to use for the configuration file
source "$binfolder/dgit-locations"

#Create the configuration file
#$confname is set by the file sourced above (dgit-locations.sh)
echo "$flinkdir/" > "$3"/"$confname"

