#!/bin/bash

#dgit--A primitive git GUI
#Copyright (C) 2011-2012  andyg0808

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#Find datadir according to spec at
#http://standards.freedesktop.org/menu-spec/menu-spec-1.1.html#third-party-howto
if [ -n "$XDG_DATA_HOME" ]
then
	datadir="$XDG_DATA_HOME"
else
	datadir="$HOME/.local/share"
fi

#Find sysconfigdir according to spec at same location
if [ -n "$XDG_CONFIG_HOME" ]
then
	sysconfdir="$XDG_CONFIG_HOME"
else
	sysconfdir="$HOME/.config"
fi

#Write each .desktop file
for file in dgit-checkout dgit-clone dgit-forget dgit-init dgit-merge
do
cat <<EOF > "$datadir/applications/dgittools-$file.desktop"
[Desktop Entry]
Type=Application
Categories=Utility
Exec=$file
Name=$file
EOF
done
